# Generated by Django 4.1.6 on 2023-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=30)),
                ('metragem', models.FloatField(max_length=4)),
            ],
        ),
    ]
